[tool.poetry]
name = "mt-system"
version = "0.0.0"  # use poetry-dynamic-versioning
description = "Python library of MT system."
authors = ["Shota Fukuda <st_fukuda@outlook.jp>"]
license = "BSD-3-Clause"
readme = "README.md"
homepage = "https://github.com/stfukuda/mt-system.git"
repository = "https://github.com/stfukuda/mt-system.git"
documentation = "https://stfukuda.github.io/mt-system/"
packages = [
    {include = "mts", from = "src"},
]
include = ["README.md"]

[tool.poetry.dependencies]
python = "^3.8"
scikit-learn = "*"

[tool.poetry.group.dev.dependencies]

[tool.poetry.group.cqa.dependencies]
isort = "*"
black = "*"
flake8 = "*"
bandit = {extras = ["toml"], version = "*"}
pre-commit = "*"

[tool.poetry.group.test.dependencies]
pytest = "*"
pytest-cov = "*"
pytest-xdis = "*"
pandas = "*"

[tool.poetry.group.docs.dependencies]
sphinx = "*"
sphinx_rtd_theme = "*"

[tool.poetry-dynamic-versioning]
enable = true

[tool.isort]
profile = "black"
lines_after_imports = 2

[tool.black]
target-version = ["py38"]

[tool.bandit]
skips = ["B101", "B601"]

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"
