name: Ruff

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "src/**/*.py"
      - "test/**/*.py"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "src/**/*.py"
      - "test/**/*.py"

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
