name: Linter

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "src/**/*.py"
      - "tests/**/*.py"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Setup Python
        uses: uv python install 3.9
      - name: Install the project
        run: uv sync --no-group test --no-group docs
      - name: Check by ruff
        run: uv run ruff check ./src ./tests
      - name: Check by bandit
        run: uv run bandit -c pyproject.toml -r ./src ./tests
