name: Test

on:
  workflow_run:
    workflows:
      - "Check"
    types:
      - "completed"
    branches:
      - main
      - develop

permissions: {}

jobs:
  test:
    name: Test (Python${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Install Test Dependencies
        run: poetry install --with Test
      - name: Test
        run: |
          poetry run pytest --cov=src --cov-report=term-missing --junit-xml results/pytest.xml
        continue-on-error: true
      - name: Upload Test Result
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: Test Result (Python${{ matrix.python-version }})
          path: results/*.xml
  publish-test-results:
    name: Publish Test Results
    needs: test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    if: always()
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          junit_files: artifacts/**/*.xml
